# -*- coding: utf-8 -*-
"""prompt_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9qGZBMOjgh-_1yWOe74k6A7T3lwk0-U
"""

def load_prompt(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read().strip()